import { Email, EmailAccount, EmailLabel } from '../types';

export const demoAccounts: EmailAccount[] = [
  { id: 'demo-1', email: 'alex.chen@gmail.com', name: 'Alex Chen', provider: 'gmail', color: '#4285f4', unreadCount: 12, connected: true },
  { id: 'demo-2', email: 'alex@outlook.com', name: 'Alex Chen', provider: 'outlook', color: '#0078d4', unreadCount: 5, connected: true },
  { id: 'demo-3', email: 'alex.c@yahoo.com', name: 'Alex C', provider: 'imap', color: '#720e9e', unreadCount: 3, connected: true },
];

export const demoLabels: EmailLabel[] = [
  { id: 'work', name: 'Work', color: '#4285f4', count: 15 },
  { id: 'personal', name: 'Personal', color: '#34a853', count: 8 },
  { id: 'finance', name: 'Finance', color: '#fbbc04', count: 4 },
  { id: 'travel', name: 'Travel', color: '#ea4335', count: 3 },
  { id: 'updates', name: 'Updates', color: '#9334e6', count: 7 },
  { id: 'design', name: 'Design', color: '#ff6d01', count: 5 },
];

const now = new Date();
const h = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 3600000).toISOString();

export const demoEmails: Email[] = [
  {
    id: 'e1', accountId: 'demo-1', threadId: 't1',
    from: { name: 'Sarah Johnson', email: 'sarah.j@acmecorp.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: 'Q3 Product Strategy — Final Review Needed',
    snippet: 'Hi Alex, I\'ve attached the final Q3 product strategy document. We need your sign-off by EOD Friday...',
    body: `Hi Alex,\n\nI've attached the final Q3 product strategy document for your review. We need your sign-off by EOD Friday to stay on track for the board presentation next Tuesday.\n\nKey changes since our last discussion:\n\n1. Revised the AI integration timeline — moved from Q4 to late Q3\n2. Added the enterprise pricing tier you suggested\n3. Updated competitive analysis with Notion's latest release\n4. Budget allocation shifted 15% toward mobile development\n\nThe team is really excited about the direction. Can you review sections 3 and 4 specifically? Those reflect the biggest strategic pivots.\n\nLet me know if you have any questions.\n\nBest,\nSarah`,
    date: h(0.5), read: false, starred: true, labels: ['work'], folder: 'inbox',
    attachments: [{ id: 'a1', name: 'Q3_Strategy_v3.pdf', size: 2400000, type: 'application/pdf' }],
    priority: 1, aiCategory: 'urgent',
    aiSummary: 'Sarah needs sign-off on the Q3 product strategy by Friday. Key changes include moving AI integration to Q3, adding enterprise pricing, and shifting 15% of budget to mobile.',
  },
  {
    id: 'e2', accountId: 'demo-1', threadId: 't2',
    from: { name: 'GitHub', email: 'notifications@github.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: '[mailmind/app] PR #247: Implement real-time sync engine',
    snippet: 'marcuswei requested your review on pull request #247. This PR implements the real-time sync...',
    body: `Marcus Wei requested your review on pull request #247\n\n## Implement real-time sync engine\n\nThis PR implements the core real-time sync engine using WebSocket connections. Changes include:\n\n- New SyncManager class with connection pooling\n- Automatic reconnection with exponential backoff\n- Delta sync for efficient bandwidth usage\n- Unit tests covering 94% of new code\n\n**Files changed:** 23\n**Additions:** +1,247\n**Deletions:** -89\n\nReview requested by @marcuswei`,
    date: h(1.2), read: false, starred: false, labels: ['work'], folder: 'inbox',
    attachments: [], priority: 2, aiCategory: 'important',
  },
  {
    id: 'e3', accountId: 'demo-1', threadId: 't3',
    from: { name: 'David Park', email: 'david.park@designstudio.io' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: 'Re: New brand identity concepts',
    snippet: 'Hey Alex! Just finished the third round of brand identity concepts. I think option C really nails...',
    body: `Hey Alex!\n\nJust finished the third round of brand identity concepts. I think option C really nails the "premium but approachable" vibe we discussed.\n\nHere's what I'm proposing:\n\n🎨 Option A — Bold & Geometric\nClean lines, strong typography, deep navy + electric blue\n\n🎨 Option B — Organic & Warm  \nSoft gradients, rounded forms, sunset palette\n\n🎨 Option C — Refined & Modern (recommended)\nSubtle gradients, Inter typeface, indigo-to-violet spectrum with glassmorphism accents\n\nI've included high-res mockups for mobile, desktop, and email templates. Let me know which direction resonates!\n\nCheers,\nDavid`,
    date: h(2.5), read: false, starred: false, labels: ['design'], folder: 'inbox',
    attachments: [
      { id: 'a2', name: 'Brand_Concepts_v3.fig', size: 15000000, type: 'application/figma' },
      { id: 'a3', name: 'Mockups_Preview.png', size: 3200000, type: 'image/png' },
    ],
    priority: 3, aiCategory: 'normal',
  },
  {
    id: 'e4', accountId: 'demo-2', threadId: 't4',
    from: { name: 'Lisa Wang', email: 'lisa.wang@techventures.vc' },
    to: [{ name: 'Alex Chen', email: 'alex@outlook.com' }],
    subject: 'Series B Follow-up — Term Sheet Discussion',
    snippet: 'Alex, great meeting yesterday. Our partners are very impressed with the traction. I wanted to...',
    body: `Alex,\n\nGreat meeting yesterday. Our partners are very impressed with the traction MailMind has shown — especially the 340% MoM growth in enterprise accounts.\n\nI wanted to follow up on a few points:\n\n1. We're prepared to lead the Series B at a $120M pre-money valuation\n2. We'd like to discuss board seat arrangements\n3. Our technical due diligence team would like to schedule a deep dive next week\n4. We can have a preliminary term sheet ready by Wednesday\n\nWould Thursday 2pm work for a follow-up call with our managing partner?\n\nLooking forward to partnering with you.\n\nBest regards,\nLisa Wang\nPartner, TechVentures Capital`,
    date: h(3), read: false, starred: true, labels: ['finance'], folder: 'inbox',
    attachments: [], priority: 1, aiCategory: 'urgent',
    aiSummary: 'TechVentures wants to lead Series B at $120M pre-money valuation. They want a follow-up call Thursday 2pm and can have a term sheet by Wednesday.',
  },
  {
    id: 'e5', accountId: 'demo-1', threadId: 't5',
    from: { name: 'Stripe', email: 'receipts@stripe.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: 'Your receipt from MailMind Pro',
    snippet: 'Payment of $29.00 successfully processed for MailMind Pro monthly subscription...',
    body: `Receipt from MailMind\n\nAmount paid: $29.00\nDate: ${new Date().toLocaleDateString()}\nPayment method: Visa ending in 4242\n\nDescription: MailMind Pro — Monthly subscription\n\nManage your subscription at dashboard.mailmind.app/billing\n\nThanks for being a Pro member!\n\n— The MailMind Team`,
    date: h(5), read: true, starred: false, labels: ['finance'], folder: 'inbox',
    attachments: [], priority: 5, aiCategory: 'newsletter',
  },
  {
    id: 'e6', accountId: 'demo-1', threadId: 't6',
    from: { name: 'Emma Rodriguez', email: 'emma.r@gmail.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: 'Dinner Saturday? 🍕',
    snippet: 'Hey! Haven\'t seen you in ages. A bunch of us are getting together Saturday night at that new...',
    body: `Hey! 👋\n\nHaven't seen you in ages. A bunch of us are getting together Saturday night at that new Italian place downtown — Trattoria Moderna. \n\nSo far it's me, Jake, Priya, and Tom. We're thinking 7:30pm?\n\nThe reviews look amazing and they have that rooftop terrace. Perfect weather for it!\n\nLet me know if you can make it! 🍝\n\n— Emma`,
    date: h(6), read: false, starred: false, labels: ['personal'], folder: 'inbox',
    attachments: [], priority: 3, aiCategory: 'normal',
  },
  {
    id: 'e7', accountId: 'demo-2', threadId: 't7',
    from: { name: 'Jira', email: 'jira@acmecorp.atlassian.net' },
    to: [{ name: 'Alex Chen', email: 'alex@outlook.com' }],
    subject: '[MAIL-1042] Critical: Email sync failing for Exchange accounts',
    snippet: 'Priority: Critical — Reporter: QA Team — Assignee: Alex Chen. Exchange email sync has been...',
    body: `MAIL-1042 — Critical Bug Report\n\nPriority: 🔴 Critical\nReporter: QA Team\nAssignee: Alex Chen\nSprint: Sprint 23\n\nDescription:\nExchange email sync has been failing intermittently for ~12% of enterprise customers since the v2.4.1 deployment. Error logs show connection timeouts after OAuth token refresh.\n\nSteps to Reproduce:\n1. Connect an Exchange/O365 account\n2. Wait for initial sync to complete\n3. After ~45 minutes, sync fails silently\n4. Manual refresh shows "Connection timeout" error\n\nExpected: Continuous sync\nActual: Sync drops after token refresh cycle\n\nAffected customers: 47 enterprise accounts\n\nPlease prioritize — this is blocking our enterprise rollout.`,
    date: h(4), read: false, starred: false, labels: ['work'], folder: 'inbox',
    attachments: [], priority: 1, aiCategory: 'urgent',
    aiSummary: 'Critical bug: Exchange email sync failing for 12% of enterprise customers (47 accounts) since v2.4.1. Connection timeouts after OAuth token refresh. Blocking enterprise rollout.',
  },
  {
    id: 'e8', accountId: 'demo-3', threadId: 't8',
    from: { name: 'Booking.com', email: 'noreply@booking.com' },
    to: [{ name: 'Alex C', email: 'alex.c@yahoo.com' }],
    subject: 'Your reservation in Tokyo is confirmed! 🇯🇵',
    snippet: 'Booking confirmation #BK-7829341. Park Hotel Tokyo, Jun 15-22. Check-in: 3:00 PM...',
    body: `Booking Confirmed! ✅\n\nConfirmation #: BK-7829341\n\n🏨 Park Hotel Tokyo\n📍 1-7-1 Higashi Shinbashi, Minato-ku, Tokyo\n📅 Check-in: June 15, 3:00 PM\n📅 Check-out: June 22, 11:00 AM\n🛏️ Deluxe King Room, City View\n💰 Total: $1,890.00 (7 nights)\n\nIncludes:\n- Daily breakfast buffet\n- Airport shuttle service\n- Free cancellation until June 10\n\nDownload the Booking.com app for easy check-in.\n\nHave a wonderful trip! 🗼`,
    date: h(8), read: true, starred: true, labels: ['travel'], folder: 'inbox',
    attachments: [], priority: 4, aiCategory: 'low',
  },
  {
    id: 'e9', accountId: 'demo-1', threadId: 't9',
    from: { name: 'The Verge', email: 'newsletter@theverge.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: 'The Verge Daily: Apple announces AI-powered email features',
    snippet: 'Plus: Google\'s new Pixel lineup leaked, Microsoft\'s Copilot gets major upgrade, and more...',
    body: `THE VERGE DAILY\n\n📱 Apple Announces AI-Powered Email Features\nApple revealed new Mail app features at WWDC, including smart summaries, priority inbox, and suggested replies powered by on-device AI.\n\n🔍 Google's New Pixel Lineup Leaked\nImages of the Pixel 10 Pro surfaced showing a radical redesign with edge-to-edge display.\n\n💼 Microsoft Copilot Gets Major Upgrade\nThe latest Copilot update brings real-time collaboration features and improved code generation.\n\n🎮 Steam Summer Sale Dates Confirmed\nValve confirms the annual sale kicks off June 26.\n\nRead more at theverge.com`,
    date: h(10), read: true, starred: false, labels: ['updates'], folder: 'inbox',
    attachments: [], priority: 5, aiCategory: 'newsletter',
  },
  {
    id: 'e10', accountId: 'demo-2', threadId: 't10',
    from: { name: 'Rachel Kim', email: 'rachel.kim@acmecorp.com' },
    to: [{ name: 'Alex Chen', email: 'alex@outlook.com' }],
    subject: 'Re: Team offsite planning — venue options',
    snippet: 'I\'ve narrowed it down to three venues. The Montecito Ranch looks perfect for our team size...',
    body: `Hi Alex,\n\nI've narrowed it down to three venues for the Q3 team offsite:\n\n1. 🏔️ Montecito Ranch Resort — $185/person/night\n   - Capacity: 50 people, 3 meeting rooms\n   - 2 hours from the office\n   - Great for team building activities\n\n2. 🌊 Coastal Retreat Center — $210/person/night\n   - Capacity: 40 people, 2 meeting rooms\n   - Oceanfront, 90 min drive\n   - Has AV equipment included\n\n3. 🌲 Redwood Lodge — $165/person/night\n   - Capacity: 60 people, 4 meeting rooms\n   - 3 hours from office\n   - Most budget-friendly\n\nI'm leaning toward Montecito — great balance of price, location, and amenities. What do you think?\n\nRachel`,
    date: h(12), read: true, starred: false, labels: ['work'], folder: 'inbox',
    attachments: [{ id: 'a4', name: 'Venue_Comparison.xlsx', size: 450000, type: 'application/xlsx' }],
    priority: 3, aiCategory: 'normal',
  },
  {
    id: 'e11', accountId: 'demo-1', threadId: 't11',
    from: { name: 'AWS', email: 'no-reply@aws.amazon.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: '⚠️ AWS Billing Alert: Unusual activity detected',
    snippet: 'Your AWS account 4821-XXXX has exceeded the estimated monthly budget of $500. Current charges...',
    body: `AWS Billing Alert\n\n⚠️ Budget Threshold Exceeded\n\nAccount: 4821-XXXX-XXXX\nCurrent month charges: $742.18\nBudget threshold: $500.00\nOverage: $242.18 (48% over budget)\n\nTop services by cost:\n1. Amazon EC2: $312.40 (+67%)\n2. Amazon RDS: $189.20 (+23%)\n3. Amazon S3: $98.50 (normal)\n4. AWS Lambda: $67.08 (+112%)\n5. CloudFront: $45.00 (normal)\n\nRecommended actions:\n- Review EC2 instance sizes\n- Check for unused resources\n- Review Lambda invocation patterns\n\nManage your budget at console.aws.amazon.com/billing`,
    date: h(7), read: false, starred: false, labels: ['work', 'finance'], folder: 'inbox',
    attachments: [], priority: 2, aiCategory: 'important',
    aiSummary: 'AWS costs exceeded $500 budget by 48% ($742 total). Main culprits: EC2 (+67%) and Lambda (+112%). Review instance sizes and Lambda invocations.',
  },
  {
    id: 'e12', accountId: 'demo-3', threadId: 't12',
    from: { name: 'Mom', email: 'linda.chen@yahoo.com' },
    to: [{ name: 'Alex C', email: 'alex.c@yahoo.com' }],
    subject: 'Dad\'s birthday dinner plans 🎂',
    snippet: 'Hi sweetheart! Just wanted to confirm — we\'re doing dad\'s birthday dinner at Golden Dragon...',
    body: `Hi sweetheart! 💕\n\nJust wanted to confirm — we're doing dad's birthday dinner at Golden Dragon next Sunday at 6pm. \n\nYour sister is bringing the cake (chocolate, his favorite). Can you pick up the gift we talked about? The watch from that store on Main Street.\n\nAlso, Aunt May and Uncle Tom are coming too, so we'll be a party of 8.\n\nDon't forget to call your dad on the actual day (Thursday)! You know how he gets 😄\n\nLove,\nMom\n\nP.S. Are you eating enough? You looked thin in your last photo! 😘`,
    date: h(14), read: false, starred: true, labels: ['personal'], folder: 'inbox',
    attachments: [], priority: 3, aiCategory: 'normal',
  },
  {
    id: 'e13', accountId: 'demo-1', threadId: 't13',
    from: { name: 'Alex Chen', email: 'alex.chen@gmail.com' },
    to: [{ name: 'Engineering Team', email: 'eng-team@acmecorp.com' }],
    subject: 'Re: Architecture decision — microservices migration',
    snippet: 'Team, after reviewing all the proposals, I think the phased approach makes the most sense...',
    body: `Team,\n\nAfter reviewing all the proposals, I think the phased approach makes the most sense. Here's my recommendation:\n\nPhase 1 (Q3): Extract auth and notification services\nPhase 2 (Q4): Migrate email processing pipeline\nPhase 3 (Q1 next year): Full API gateway implementation\n\nThis gives us quick wins while managing risk. Thoughts?\n\n— Alex`,
    date: h(20), read: true, starred: false, labels: ['work'], folder: 'sent',
    attachments: [], priority: 3, aiCategory: 'normal',
  },
  {
    id: 'e14', accountId: 'demo-1', threadId: 't14',
    from: { name: 'LinkedIn', email: 'notifications@linkedin.com' },
    to: [{ name: 'Alex Chen', email: 'alex.chen@gmail.com' }],
    subject: '3 people viewed your profile this week',
    snippet: 'See who\'s been checking out your profile: VP of Engineering at TechCorp, Senior Recruiter...',
    body: `Your weekly profile views\n\n👀 3 people viewed your profile:\n\n1. VP of Engineering at TechCorp\n2. Senior Recruiter at Meta\n3. CTO at StartupXYZ\n\nYour profile appeared in 47 searches this week.\n\nUpdate your profile to attract more views.`,
    date: h(24), read: true, starred: false, labels: ['updates'], folder: 'inbox',
    attachments: [], priority: 5, aiCategory: 'newsletter',
  },
  {
    id: 'e15', accountId: 'demo-2', threadId: 't15',
    from: { name: 'Security Team', email: 'security@acmecorp.com' },
    to: [{ name: 'Alex Chen', email: 'alex@outlook.com' }],
    subject: '🔒 Mandatory: Complete annual security training by May 30',
    snippet: 'This is a reminder to complete your annual information security training. Deadline: May 30...',
    body: `Hi Alex,\n\nThis is a reminder to complete your annual information security training.\n\n📅 Deadline: May 30, 2024\n⏱️ Estimated time: 45 minutes\n🔗 Link: security.acmecorp.com/training\n\nTopics covered:\n- Phishing awareness\n- Data handling policies\n- Password best practices\n- Incident reporting procedures\n\nCompletion is mandatory for all employees. Failure to complete by the deadline may result in restricted system access.\n\nThank you,\nInformation Security Team`,
    date: h(30), read: true, starred: false, labels: ['work'], folder: 'inbox',
    attachments: [], priority: 2, aiCategory: 'important',
  },
];
